### ISSUE TITLE
No option to create Binding in cloudflare worker dashboard.

### ISSUE THREAD

**Issue by akkiverma** [cloudflare/worker-examples#37]
Hello,

Since Cloudflare started offering free daily workers, I thought to configure this. 

Since workers KV is not available in the free account, I decided to go via the API method.

Added the script > opened Resources, clicked "Add binding"

Now it does show an option to add `VARIABLE NAME` but doesn't show the option of adding `NAMESPACE`.

Rather it asks to add a WASM file which I have no idea of. 

Can you please help in sharing what would be the content of WASM file?

**Comment by akkiverma** [comment]
So, in short, I don't get the option to add NAMESPACE binding, so how to manage this without it?

**Comment by pmeenan** [comment]
Looks like the UI has changed and KV is a tab in the new workers dashboard. Best bet is probably to ping support and see what the current way to set up a binding to KV is.  It is completely separate from the WASM bindings.

**Comment by kentonv** [comment]
Hi @akkiverma,

While Workers now has a free tier, Workers KV does not (yet). In order to use KV, you'll need to subscribe to the paid Workers product.

**Comment by alriksson** [comment]
Is only the KV workers paid and the default for free nowadays?

@pmeenan Is there an issue for the streamers to work with shared kv between the sites. Worried it could cause issues when it's not binded separately on each applicaiton

**Comment by kentonv** [comment]
@alriksson Sorry, I don't understand your question. As of a week ago, Workers can be used for free, albeit with a strict limit on total requests served and no KV; see: https://workers.cloudflare.com/ In order to remove the request limit and get access to KV, you need to upgrade to the $5/month (+usage) Workers subscription plan.

**Comment by alriksson** [comment]
Ok so the normal worker is free and the kv is paid? Even when not using the workers.dev domains. Meaning I can use free workers within my account and application and domain?

Using the KV right now but some applications I might consider the free instead of nothing if it can be used as the previous worker worked. Which was just missing kv features.

**Comment by kentonv** [comment]
@alriksson You can use free workers on a real domain, but you only get 100k requests/day across your whole account on the free plan, and performance might be slightly worse (e.g. the first request might take an extra 200ms or so). If you want more requests than that, or better performance, or KV, then you need to upgrade to a paid plan.

**Comment by alriksson** [comment]
@kentonv Understood and what I thought and expected. Just wanted to get it confirmed.

100% agree but some low priority sites can utilize the free version, to begin with until we hit the bar or traffic etc.

Thanks!
